### ISSUE TITLE
performWebRequest is not defined

### ISSUE THREAD

**Issue by xuanzz** [winstonma/MMM-HK-Transport-ETA#5]
Hi Winston,
Thank you for creating this module. However, when I attempt to integrate it into my MM, the module continuously displays "Loading...". The console provides the following message:
Could not load data ...  ReferenceError: performWebRequest is not defined
    at Class.fetchData (hktransportetaprovider.js:84:3)
    at Class.fetchStationInfo (mtr.js:45:15)
    at Class.fetchETA (mtr.js:30:38)
    at MMM-HK-Transport-ETA.js:183:30
(anonymous) @ mtr.js:64

**Comment by winstonma** [comment]
Hi, I guess it is because the [utils.js](https://github.com/MichMich/MagicMirror/blob/e87f50e64aeaf3a8587f4855f4679c3223959fd0/modules/default/utils.js#L10) was missing, which was introduced in MagicMirror v2.22.0.

Could you try updating your MagicMirror following the [Upgrade Guide](https://docs.magicmirror.builders/getting-started/upgrade-guide.html) and see if that works for you?

**Comment by xuanzz** [comment]
Thanks for the hints. I am running "[ich777/magic-mirror2](https://hub.docker.com/r/ich777/magic-mirror2)" on my UNRAID server. The file was missing initially. I first tried to add the file to the path, but it didn't work. Then, after recreating the container, the file was present and everything works perfectly now!

**Comment by winstonma** [comment]
Let me close this ticket for now. And please feel free to reopen if you face any issue.
